import { CloudAccount, FileItem, FolderItem, SharedLibrary, AppNotification, RemovableDevice } from '../types';

export const INITIAL_ACCOUNTS: CloudAccount[] = [
  {
    id: 'gdrive',
    name: 'Google Drive',
    provider: 'Google Drive',
    email: 'you@example.com',
    avatarColor: 'from-amber-500 to-emerald-500',
    usedBytes: 74.2 * 1024 * 1024 * 1024,
    totalBytes: 200 * 1024 * 1024 * 1024,
    status: 'connected',
    encryptionLevel: 'Standard TLS',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    provider: 'Dropbox',
    email: 'creative@example.com',
    avatarColor: 'from-blue-600 to-indigo-600',
    usedBytes: 1.18 * 1024 * 1024 * 1024 * 1024,
    totalBytes: 2.0 * 1024 * 1024 * 1024 * 1024,
    status: 'connected',
    encryptionLevel: 'Standard TLS',
  },
  {
    id: 's3',
    name: 'OneDrive',
    provider: 'OneDrive',
    email: 'you@example.com',
    avatarColor: 'from-blue-500 to-sky-600',
    usedBytes: 482.6 * 1024 * 1024 * 1024,
    totalBytes: 1024 * 1024 * 1024 * 1024,
    status: 'connected',
    encryptionLevel: 'Client E2EE AES-256',
  },
  {
    id: 'cloudflare_r2',
    name: 'MEGA Drive',
    provider: 'MEGA Drive',
    email: 'you@example.com',
    avatarColor: 'from-red-500 to-rose-600',
    usedBytes: 18.4 * 1024 * 1024 * 1024,
    totalBytes: 50 * 1024 * 1024 * 1024,
    status: 'connected',
    encryptionLevel: 'Zero-Knowledge Vault',
  },
  {
    id: 'nextcloud',
    name: 'NextCloud',
    provider: 'Nextcloud',
    email: 'you@example.com',
    avatarColor: 'from-blue-600 via-sky-500 to-cyan-400',
    usedBytes: 148.6 * 1024 * 1024 * 1024,
    totalBytes: 500 * 1024 * 1024 * 1024,
    status: 'connected',
    encryptionLevel: 'Client E2EE AES-256',
  },
];

export const INITIAL_FOLDERS: FolderItem[] = [
  { id: 'f-desktop', name: 'Desktop', accountId: 'all', itemCount: 4 },
  { id: 'f-documents', name: 'Documents', accountId: 'all', itemCount: 3 },
  { id: 'f-photos', name: 'Photos', accountId: 'all', itemCount: 8 },
  { id: 'f-videos', name: 'Videos', accountId: 'all', itemCount: 6 },
  { id: 'f-downloads', name: 'Downloads', accountId: 'all', itemCount: 5 },
  { id: 'f-applications', name: 'Applications', accountId: 'all', itemCount: 12 },
  { id: 'f-trash', name: 'Trash', accountId: 'all', itemCount: 2 },
];

export const INITIAL_REMOVABLE_DEVICES: RemovableDevice[] = [
  {
    id: 'dev-sandisk',
    name: 'SanDisk Extreme Pro',
    mountPoint: '/Volumes/SanDisk-2TB',
    type: 'nvme_ssd',
    fileSystem: 'APFS Encrypted',
    capacityBytes: 2 * 1024 * 1024 * 1024 * 1024,
    freeBytes: 1.42 * 1024 * 1024 * 1024 * 1024,
    encrypted: true,
    mounted: true,
    ejectable: true,
    connectionType: 'USB-C 3.2',
  },
  {
    id: 'dev-samsung-t7',
    name: 'Samsung T7 Shield',
    mountPoint: '/Volumes/T7-Shield',
    type: 'nvme_ssd',
    fileSystem: 'ExFAT',
    capacityBytes: 1024 * 1024 * 1024 * 1024,
    freeBytes: 620 * 1024 * 1024 * 1024,
    encrypted: false,
    mounted: true,
    ejectable: true,
    connectionType: 'USB-C 3.2',
  },
  {
    id: 'dev-sony-cfexpress',
    name: 'Sony CFexpress Type A',
    mountPoint: '/Volumes/ALPHA-CARD1',
    type: 'memory_card',
    fileSystem: 'ExFAT (Sony Cinema)',
    capacityBytes: 160 * 1024 * 1024 * 1024,
    freeBytes: 42.8 * 1024 * 1024 * 1024,
    encrypted: false,
    mounted: true,
    ejectable: true,
    connectionType: 'CFexpress / SD',
  },
  {
    id: 'dev-lacie-raid',
    name: 'LaCie Rugged RAID',
    mountPoint: '/Volumes/LaCie-RAID0',
    type: 'thunderbolt_raid',
    fileSystem: 'APFS Hardware RAID',
    capacityBytes: 4 * 1024 * 1024 * 1024 * 1024,
    freeBytes: 2.85 * 1024 * 1024 * 1024 * 1024,
    encrypted: true,
    mounted: true,
    ejectable: true,
    connectionType: 'Thunderbolt 4',
  },
];

export const INITIAL_FILES: FileItem[] = [
  {
    id: 'file-vid-1',
    name: 'Pacific_Coast_Cinematic_B-Roll_4K.mp4',
    folderId: 'f-videos',
    folderPath: '/Videos',
    accountId: 's3',
    sizeBytes: 148 * 1024 * 1024,
    category: 'video',
    mimeType: 'video/mp4',
    updatedAt: '2026-10-04T18:24:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    url: '/sample-video.mp4',
    starred: true,
    tags: ['4K', 'Cinematic', 'B-Roll', 'Ocean', 'ProRes-Proxy'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '9c:a1:83:fe:72:0b:da:51:98:3c:e4:aa',
      checksumSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      zeroKnowledgeVerified: true,
    },
    videoMeta: {
      durationSeconds: 15.02,
      dimensions: { width: 3840, height: 2160 },
      framerate: 59.94,
      codec: 'H.264 High Profile',
      bitrate: '45.2 Mbps',
      audioCodec: 'AAC-LC 320kbps 48kHz Stereo',
    },
    version: 3,
  },
  {
    id: 'file-photo-1',
    name: 'Editorial_Nordic_Architectural_Still.jpg',
    folderId: 'f-photos',
    folderPath: '/Photos',
    accountId: 'dropbox',
    sizeBytes: 18.4 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/jpeg',
    updatedAt: '2026-10-05T09:12:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2400&q=85',
    starred: true,
    tags: ['Architecture', 'Minimalism', 'Interior', 'Editorial'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None (TLS 1.3)',
      keyFingerprint: 'Unencrypted Transit',
      checksumSha256: '8f7a62b3c10940562e845f91753a870d0bf3d5671192',
      zeroKnowledgeVerified: false,
    },
    photoExif: {
      camera: 'Sony Alpha 1',
      lens: 'FE 24-70mm F2.8 GM II',
      focalLength: '35mm',
      aperture: 'f/4.0',
      shutterSpeed: '1/250s',
      iso: 100,
      dimensions: { width: 8640, height: 5760 },
      colorSpace: 'Display P3',
    },
    version: 1,
  },
  {
    id: 'file-vid-2',
    name: 'Urban_Night_Hyperlapse_Tokyo.mp4',
    folderId: 'f-videos',
    folderPath: '/Videos',
    accountId: 's3',
    sizeBytes: 94.6 * 1024 * 1024,
    category: 'video',
    mimeType: 'video/mp4',
    updatedAt: '2026-10-03T21:40:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    url: '/sample-video.mp4',
    starred: false,
    tags: ['Hyperlapse', 'Neon', 'Tokyo', 'Nightscape'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '77:0e:92:aa:19:bc:43:80:61:cd:2b:ff',
      checksumSha256: 'bc91c00293da826efba1239c0175b923ca01f568a01',
      zeroKnowledgeVerified: true,
    },
    videoMeta: {
      durationSeconds: 15.0,
      dimensions: { width: 1920, height: 1080 },
      framerate: 60,
      codec: 'HEVC / H.265',
      bitrate: '28.4 Mbps',
      audioCodec: 'Stereo AAC',
    },
    version: 2,
  },
  {
    id: 'file-photo-2',
    name: 'High_Desert_Monolith_Sunset.jpg',
    folderId: 'f-photos',
    folderPath: '/Photos',
    accountId: 'gdrive',
    sizeBytes: 14.2 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/jpeg',
    updatedAt: '2026-10-05T14:30:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=2400&q=85',
    starred: true,
    tags: ['Golden Hour', 'Landscape', 'Warmth', 'Raw Grade'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '41:d9:e5:08:7a:33:66:91:ff:00:c3:2b',
      checksumSha256: '9a34ff12bb33560129bccefa8830114f092301cba2',
      zeroKnowledgeVerified: true,
    },
    photoExif: {
      camera: 'Hasselblad X2D 100C',
      lens: 'XCD 55mm f/2.5 V',
      focalLength: '55mm',
      aperture: 'f/5.6',
      shutterSpeed: '1/60s',
      iso: 64,
      dimensions: { width: 11656, height: 8742 },
      colorSpace: 'Hasselblad Natural Color Solution (HNCS)',
    },
    version: 4,
  },
  {
    id: 'file-photo-3',
    name: 'Cyber_Street_Portrait_Neon.jpg',
    folderId: 'f-photos',
    folderPath: '/Photos',
    accountId: 'dropbox',
    sizeBytes: 21.8 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/jpeg',
    updatedAt: '2026-10-02T11:15:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=2400&q=85',
    starred: false,
    tags: ['Portrait', 'Studio', 'Editorial', 'High Contrast'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '12:8f:5e:30:1a:2b:88:c0:94:01:aa:ef',
      checksumSha256: '48bb201201ccff294025110aa049281e0128470a1',
      zeroKnowledgeVerified: true,
    },
    photoExif: {
      camera: 'Leica SL2-S',
      lens: 'Summilux-SL 50mm f/1.4 ASPH',
      focalLength: '50mm',
      aperture: 'f/1.4',
      shutterSpeed: '1/1000s',
      iso: 200,
      dimensions: { width: 6000, height: 4000 },
      colorSpace: 'Adobe RGB 1998',
    },
    version: 1,
  },
  {
    id: 'file-vid-3',
    name: 'Alpine_Snowfield_Drone_Survey_4K.mp4',
    folderId: 'f-videos',
    folderPath: '/Videos',
    accountId: 's3',
    sizeBytes: 215 * 1024 * 1024,
    category: 'video',
    mimeType: 'video/mp4',
    updatedAt: '2026-09-28T16:04:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    url: '/sample-video.mp4',
    starred: true,
    tags: ['Drone', 'Mountains', '60fps', 'Master'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '88:22:90:bc:ef:31:07:aa:34:21:60:df',
      checksumSha256: 'aa014859012f4837a0129bc574880193bb582103',
      zeroKnowledgeVerified: true,
    },
    videoMeta: {
      durationSeconds: 596.0,
      dimensions: { width: 1920, height: 1080 },
      framerate: 30,
      codec: 'AVC / H.264',
      bitrate: '18.9 Mbps',
      audioCodec: 'Vorbis Stereo',
    },
    version: 1,
  },
  {
    id: 'file-doc-1',
    name: 'Brand_Strategy_And_Visual_Language_2026.pdf',
    folderId: 'f-documents',
    folderPath: '/Documents',
    accountId: 'gdrive',
    sizeBytes: 8.5 * 1024 * 1024,
    category: 'document',
    mimeType: 'application/pdf',
    updatedAt: '2026-10-04T10:00:00Z',
    url: '#',
    starred: false,
    tags: ['Guidelines', 'Brand', 'Confidential'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '99:00:aa:22:bb:33:44:dd:ee:55:ff:11',
      checksumSha256: 'fa30194820102b48902c3848011ccba49019203a',
      zeroKnowledgeVerified: true,
    },
    version: 6,
  },
  {
    id: 'file-vault-1',
    name: 'Financial_Ledger_And_Key_Shares_Q3.enc',
    folderId: 'f-desktop',
    folderPath: '/Desktop',
    accountId: 'vault',
    sizeBytes: 4.2 * 1024 * 1024,
    category: 'archive',
    mimeType: 'application/octet-stream',
    updatedAt: '2026-10-01T08:00:00Z',
    url: '#',
    starred: true,
    tags: ['E2EE', 'Zero-Knowledge', 'Financial', 'Top Secret'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM + Argon2id',
      keyFingerprint: 'ff:ff:3a:8c:12:09:bd:01:ee:44:90:38',
      checksumSha256: '38a901004fa9201bc89401923ba48102ff940182',
      zeroKnowledgeVerified: true,
    },
    version: 2,
  },
  {
    id: 'file-nextcloud-1',
    name: 'Nextcloud_Federated_Storage_Catalog.pdf',
    folderId: 'f-documents',
    folderPath: '/Documents',
    accountId: 'nextcloud',
    sizeBytes: 8.4 * 1024 * 1024,
    category: 'document',
    mimeType: 'application/pdf',
    updatedAt: '2026-10-06T10:15:00Z',
    url: '#',
    starred: true,
    tags: ['Nextcloud', 'WebDAV', 'Federation', 'Self-Hosted'],
    encryption: {
      isEncrypted: true,
      algorithm: 'AES-256-GCM',
      keyFingerprint: '4a:71:0d:fe:88:22:90:ac:11:39:ee:b1',
      checksumSha256: '99bf21a004ec90123561499214df904321774320',
      zeroKnowledgeVerified: true,
    },
    version: 1,
  },
  {
    id: 'file-photo-4',
    name: 'Abstract_Glass_Prism_Caustics.png',
    folderId: 'f-downloads',
    folderPath: '/Downloads',
    accountId: 'cloudflare_r2',
    sizeBytes: 12.6 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/png',
    updatedAt: '2026-10-03T14:18:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=2400&q=85',
    starred: false,
    tags: ['Prism', '3D', 'Caustics', 'Textures'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None (TLS 1.3)',
      keyFingerprint: 'Unencrypted Transit',
      checksumSha256: '109248bbff490192cb28491024aa8491024baef0',
      zeroKnowledgeVerified: false,
    },
    photoExif: {
      camera: 'Render Engine: Octane 2026',
      lens: '100mm Macro Tilt-Shift',
      dimensions: { width: 4096, height: 4096 },
      colorSpace: 'ACEScg Wide Gamut',
    },
    version: 1,
  },
  {
    id: 'file-trash-1',
    name: 'Deleted_Rough_Cut_Draft_v01.mp4',
    folderId: 'f-trash',
    folderPath: '/Trash',
    accountId: 'all',
    sizeBytes: 42.5 * 1024 * 1024,
    category: 'video',
    mimeType: 'video/mp4',
    updatedAt: '2026-09-28T16:20:00Z',
    url: '/sample-video.mp4',
    starred: false,
    tags: ['Trash', 'Outdated', 'Draft'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None',
      keyFingerprint: 'Trashed Item',
      checksumSha256: '9182390a8f10bc93',
      zeroKnowledgeVerified: false,
    },
    version: 1,
  },
  {
    id: 'file-trash-2',
    name: 'Archived_Temporary_Raw_Notes.pdf',
    folderId: 'f-trash',
    folderPath: '/Trash',
    accountId: 'all',
    sizeBytes: 1.8 * 1024 * 1024,
    category: 'document',
    mimeType: 'application/pdf',
    updatedAt: '2026-09-29T11:05:00Z',
    url: '#',
    starred: false,
    tags: ['Trash', 'Notes', 'Temp'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None',
      keyFingerprint: 'Trashed Item',
      checksumSha256: 'bc91c00293da826e',
      zeroKnowledgeVerified: false,
    },
    version: 1,
  },
  {
    id: 'file-nas-1',
    name: 'Studio_Lobby_Reference_Shoot.jpg',
    folderPath: '/Projects/Reference',
    accountId: 'all',
    sourceId: 'Studio NAS (10GbE SMB)',
    sizeBytes: 21.3 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/jpeg',
    updatedAt: '2026-10-02T12:00:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2400&q=85',
    tags: ['NAS', 'Reference'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None (local volume)',
      keyFingerprint: 'Unencrypted',
      checksumSha256: '',
      zeroKnowledgeVerified: false,
    },
    version: 1,
  },
  {
    id: 'file-nas-2',
    name: 'Tokyo_Night_Street_Selects.jpg',
    folderPath: '/Projects/Selects',
    accountId: 'all',
    sourceId: 'Studio NAS (10GbE SMB)',
    sizeBytes: 16.8 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/jpeg',
    updatedAt: '2026-10-03T12:00:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2400&q=85',
    tags: ['NAS', 'Selects'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None (local volume)',
      keyFingerprint: 'Unencrypted',
      checksumSha256: '',
      zeroKnowledgeVerified: false,
    },
    version: 1,
  },
  {
    id: 'file-dev-1',
    name: 'Beach_Sunrise_RAW_Export.jpg',
    folderPath: '/DCIM/100MSDCF',
    accountId: 'all',
    sourceId: 'dev-sandisk',
    sizeBytes: 24.5 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/jpeg',
    updatedAt: '2026-10-04T12:00:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2400&q=85',
    tags: ['Device', 'RAW'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None (local volume)',
      keyFingerprint: 'Unencrypted',
      checksumSha256: '',
      zeroKnowledgeVerified: false,
    },
    version: 1,
  },
  {
    id: 'file-dev-2',
    name: 'Gradient_Texture_Pack_Master.png',
    folderPath: '/Exports',
    accountId: 'all',
    sourceId: 'dev-sandisk',
    sizeBytes: 12.1 * 1024 * 1024,
    category: 'photo',
    mimeType: 'image/png',
    updatedAt: '2026-10-05T12:00:00Z',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=2400&q=85',
    tags: ['Device', 'Textures'],
    encryption: {
      isEncrypted: false,
      algorithm: 'None (local volume)',
      keyFingerprint: 'Unencrypted',
      checksumSha256: '',
      zeroKnowledgeVerified: false,
    },
    version: 1,
  },
];

export const INITIAL_SHARED_LIBRARIES: SharedLibrary[] = [
  {
    id: 'lib-2',
    name: 'Editorial Architecture Lookbook',
    description: 'High-res interior captures, color LUT comparisons, and print master layouts received via encrypted P2P.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Elena Rostova',
    ownerEmail: 'elena@example.com',
    memberCount: 3,
    accountId: 'dropbox',
    fileIds: ['file-photo-1', 'file-photo-3'],
    role: 'editor',
    e2eeProtected: true,
    createdAt: '2026-09-25',
    direction: 'incoming',
    // P2P Incoming Protocol Data
    senderPeerName: 'Elena Rostova',
    senderPeerEmail: 'elena@example.com',
    senderPeerNodeId: 'peer-cph-node-042',
    p2pProtocol: 'Encrypted P2P (Noise XX + AES-256-GCM)',
    p2pEncryptionCipher: 'AES-256-GCM Zero-Knowledge',
    p2pSwarmPeers: 3,
    incomingStatus: 'synced',
    transferSpeed: '42.8 MB/s',
    members: [
      { id: 'm-2', name: 'Elena Rostova (Sender Peer)', email: 'elena@example.com', role: 'admin', status: 'active' },
      { id: 'm-1', name: 'Steven Azevedo (You)', email: 'you@example.com', role: 'editor', status: 'active' },
      { id: 'm-6', name: 'Clara Oswald', email: 'clara@example.com', role: 'viewer', status: 'active' },
    ],
  },
  {
    id: 'lib-4',
    name: 'Tokyo Commercial Dailies VFX',
    description: 'High-framerate RED Monstro 8K cinema footage and graded plates received via encrypted direct P2P stream.',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Marcus Chen',
    ownerEmail: 'm.chen@example.com',
    memberCount: 4,
    accountId: 's3',
    fileIds: ['file-vid-1', 'file-vid-2'],
    role: 'editor',
    e2eeProtected: true,
    createdAt: '2026-10-02',
    direction: 'incoming',
    // P2P Incoming Protocol Data
    senderPeerName: 'Marcus Chen',
    senderPeerEmail: 'm.chen@example.com',
    senderPeerNodeId: 'peer-tyo-shibuya-81',
    p2pProtocol: 'Direct Encrypted P2P (QUIC Stream)',
    p2pEncryptionCipher: 'ChaCha20-Poly1305 + Curve25519',
    p2pSwarmPeers: 4,
    incomingStatus: 'streaming',
    transferSpeed: '64.1 MB/s',
    members: [
      { id: 'm-3', name: 'Marcus Chen (Sender Peer)', email: 'm.chen@example.com', role: 'admin', status: 'active' },
      { id: 'm-1', name: 'Steven Azevedo (You)', email: 'you@example.com', role: 'editor', status: 'active' },
      { id: 'm-4', name: 'Sarah Sterling', email: 'sarah@example.com', role: 'viewer', status: 'active' },
    ],
  },
  {
    id: 'lib-1',
    name: 'Autumn Global Brand Reel 2026',
    description: 'Master grading stills, 4K b-roll sequences, and soundtrack revisions currently seeding to specified P2P users.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Steven Azevedo',
    ownerEmail: 'you@example.com',
    memberCount: 5,
    accountId: 's3',
    fileIds: ['file-vid-1', 'file-vid-2', 'file-photo-2'],
    role: 'owner',
    e2eeProtected: true,
    createdAt: '2026-09-20',
    direction: 'outgoing',
    // P2P Outgoing Seeding Data
    isSeeding: true,
    seedingStatus: 'active',
    p2pProtocol: 'Zero-Knowledge P2P Seeder',
    p2pEncryptionCipher: 'AES-256-GCM E2EE Stream',
    transferSpeed: '32.7 MB/s',
    seedingBandwidthCap: '100 MB/s',
    seedingPeers: [
      { id: 'p-1', name: 'Elena Rostova', email: 'elena@example.com', peerNodeId: 'peer-cph-node-042', status: 'seeding', transferSpeed: '14.2 MB/s', progressPercent: 92, role: 'editor', publicKey: '0x8f2a...1a09' },
      { id: 'p-2', name: 'Marcus Chen', email: 'm.chen@example.com', peerNodeId: 'peer-tyo-shibuya-81', status: 'seeding', transferSpeed: '18.5 MB/s', progressPercent: 88, role: 'editor', publicKey: '0x3c99...bb21' },
      { id: 'p-3', name: 'Sarah Sterling', email: 'sarah@example.com', peerNodeId: 'peer-sfo-relay-19', status: 'connected', transferSpeed: '0.0 MB/s', progressPercent: 100, role: 'viewer', publicKey: '0x7e41...90fe' },
      { id: 'p-4', name: 'David Kim', email: 'david@example.com', peerNodeId: 'peer-icn-seoul-05', status: 'pending', transferSpeed: '0.0 MB/s', progressPercent: 0, role: 'viewer', publicKey: '0x11ab...65d4' },
    ],
    members: [
      { id: 'm-1', name: 'Steven Azevedo (Seeder Host)', email: 'you@example.com', role: 'admin', status: 'active' },
      { id: 'm-2', name: 'Elena Rostova', email: 'elena@example.com', role: 'editor', status: 'active' },
      { id: 'm-3', name: 'Marcus Chen', email: 'm.chen@example.com', role: 'editor', status: 'active' },
      { id: 'm-4', name: 'Sarah Sterling', email: 'sarah@example.com', role: 'viewer', status: 'active' },
      { id: 'm-5', name: 'David Kim', email: 'david@example.com', role: 'viewer', status: 'pending' },
    ],
  },
  {
    id: 'lib-3',
    name: 'Encrypted Sovereign Asset Vault',
    description: 'Private financial models, biometric keys, and contracts seeding exclusively to designated P2P keyholders.',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Steven Azevedo',
    ownerEmail: 'you@example.com',
    memberCount: 2,
    accountId: 'vault',
    fileIds: ['file-vault-1'],
    role: 'owner',
    e2eeProtected: true,
    createdAt: '2026-10-01',
    direction: 'outgoing',
    // P2P Outgoing Seeding Data
    isSeeding: true,
    seedingStatus: 'active',
    p2pProtocol: 'Sovereign Direct Peer Seeder',
    p2pEncryptionCipher: 'AES-256-GCM + Argon2id Zero-Knowledge',
    transferSpeed: '12.4 MB/s',
    seedingBandwidthCap: '50 MB/s',
    seedingPeers: [
      { id: 'p-counsel', name: 'Legal Counsel (Key Holder)', email: 'keys@example.com', peerNodeId: 'node-vault-is-77', status: 'seeding', transferSpeed: '12.4 MB/s', progressPercent: 100, role: 'viewer', publicKey: '0x4f12...bc90' },
    ],
    members: [
      { id: 'm-1', name: 'Steven Azevedo (Seeder Host)', email: 'you@example.com', role: 'admin', status: 'active' },
      { id: 'm-7', name: 'Legal Counsel (Key Holder)', email: 'keys@example.com', role: 'viewer', status: 'active' },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'incoming_library',
    title: 'Incoming P2P Media Library Request',
    message: 'Liam Vance (Vance Cinema) sent an incoming media library via encrypted direct P2P protocol: "Copenhagen Architectural Documentary". Accept to mount and stream files.',
    timestamp: '10m ago',
    read: false,
    status: 'pending',
    sender: {
      name: 'Liam Vance',
      email: 'liam@example.com',
      peerNodeId: 'peer-cph-vance-99',
    },
    libraryData: {
      name: 'Copenhagen Architectural Documentary',
      description: '8K architectural stills, RAW cinema plates, and director color LUTs.',
      coverImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      fileIds: ['file-photo-1', 'file-photo-2', 'file-photo-3'],
      p2pProtocol: 'Encrypted P2P (Noise XX + AES-256-GCM)',
      transferSpeed: '54.2 MB/s',
      sizeBytes: 6.8 * 1024 * 1024 * 1024,
      itemCount: 14,
    },
  },
  {
    id: 'notif-2',
    type: 'incoming_library',
    title: 'Incoming P2P Media Library Request',
    message: 'Dr. Aris Thorne (Sovereign Optics) sent an incoming encrypted media library: "Deep Space Spectral Stills (Octane ACES)". Accept to start verified peer synchronization.',
    timestamp: '45m ago',
    read: false,
    status: 'pending',
    sender: {
      name: 'Dr. Aris Thorne',
      email: 'aris@example.com',
      peerNodeId: 'node-reykjavik-optics-01',
    },
    libraryData: {
      name: 'Deep Space Spectral Stills',
      description: 'Ultra-wide chromatic astrophotography scans with ACEScg color space grading.',
      coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
      fileIds: ['file-photo-4', 'file-vid-2'],
      p2pProtocol: 'Direct QUIC Encrypted P2P',
      transferSpeed: '38.6 MB/s',
      sizeBytes: 4.2 * 1024 * 1024 * 1024,
      itemCount: 8,
    },
  },
  {
    id: 'notif-3',
    type: 'seeding_event',
    title: 'Peer Connected to Outgoing Seeding Stream',
    message: 'Marcus Chen connected to your outgoing seeding stream for "Autumn Global Brand Reel 2026". Currently uploading encrypted chunks at 18.5 MB/s.',
    timestamp: '2h ago',
    read: true,
  },
  {
    id: 'notif-4',
    type: 'security',
    title: 'Zero-Knowledge Cryptographic Handshake Verified',
    message: 'Noise-XX authenticated session renewed with Studio NAS relay node (192.168.1.100). E2EE cipher pipeline operational.',
    timestamp: '4h ago',
    read: true,
  },
  {
    id: 'notif-5',
    type: 'storage',
    title: 'Unified Storage Quota Notice',
    message: 'Allocated cloud bucket space is currently at 68% (1.42 TB / 2.08 TB used). High-speed zero-knowledge cache has 660 GB available.',
    timestamp: 'Yesterday',
    read: true,
  },
];
